server:
  port: 8088
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///zq_kaoshi?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: /mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lening.entity



